/**
 * Shopware 6.7 default storefront selectors (verified against the demo shop).
 *
 * These rely on Shopware core CSS classes / ids / form field names — NOT on
 * visible texts — so they work regardless of storefront language.
 * Themes that change markup override single keys in projects/<name>.ts
 * via `selectors: { header: { cart: '.my-cart' } }`.
 */
export const shopware67Selectors = {
  page: {
    /** <body> class prefixes Shopware sets per controller/action */
    body: 'body',
    main: 'main.content-main, main',
    breadcrumb: '.breadcrumb',
    alertSuccess: '.alert-success',
    alertDanger: '.alert-danger',
    alertInfo: '.alert-info',
    invalidField: '.is-invalid',
    invalidFeedback: '.invalid-feedback',
    loader: '.loader, .element-loader-backdrop',
  },
  cookie: {
    banner: '.cookie-permission-container',
    onlyNecessary: '.js-cookie-permission-button',
    acceptAll: '.js-cookie-accept-all-button',
    configure: '.js-cookie-configuration-button',
  },
  header: {
    root: 'header, .header-main',
    logo: '.header-logo-main-link',
    searchInput: '.header-search-input',
    searchButton: '.header-search-btn',
    /** mobile: search field is collapsed behind a toggle button */
    searchToggle: '.js-search-toggle-btn, .search-toggle-btn, [data-bs-target="#searchCollapse"], [aria-controls="searchCollapse"]',
    /** the outer .search-suggest wrapper has zero width — target the visible list */
    searchSuggest: '.search-suggest-container',
    searchSuggestProduct: '.search-suggest-product',
    cart: '.header-cart',
    cartTotal: '.header-cart-total',
    cartBadge: '.header-cart-badge',
    accountButton: '#accountWidget, .account-menu-btn',
    accountDropdown: '.account-menu-dropdown',
    accountLoginLink: '.account-menu-login-button',
    accountLogoutLink: 'a[href$="/account/logout"]',
    wishlist: '.header-wishlist',
    wishlistBadge: '.header-wishlist-badge',
    mobileMenuToggle: '.nav-main-toggle-btn',
    languageSwitch: '.top-bar-language',
    currencySwitch: '.top-bar-currency',
  },
  navigation: {
    root: '.main-navigation, nav.main-navigation-menu',
    link: '.main-navigation-link',
    rootLink: '.main-navigation-link.root',
    homeLink: '.main-navigation-link.home-link',
    /** 6.7 renders flyouts as Bootstrap dropdowns; older themes use .navigation-flyout */
    flyout: '.main-navigation-menu .dropdown-menu, .navigation-flyout',
    flyoutLink: '.navigation-flyout-link',
    offcanvas: '.offcanvas.show',
    offcanvasLink: '.navigation-offcanvas-link',
    offcanvasClose: '.offcanvas-close',
  },
  listing: {
    root: '.cms-element-product-listing',
    productBox: '.product-box',
    productName: '.product-name',
    productPrice: '.product-price',
    listPrice: '.list-price',
    productImage: '.product-image-wrapper img',
    buyButton: '.btn-buy',
    wishlistButton: '.product-wishlist-action',
    sorting: 'select.sorting',
    pagination: '.pagination',
    paginationItem: '.pagination .page-item',
    paginationNext: '.pagination .page-next',
    filterPanel: '.filter-panel',
    filterPanelToggle: '.filter-panel-wrapper-toggle',
    filterItem: '.filter-panel-item',
    filterItemToggle: '.filter-panel-item-toggle',
    filterOption: '.filter-multi-select-list-item',
    filterOptionCheckbox: '.filter-multi-select-list-item input[type="checkbox"]',
    filterManufacturer: '.filter-multi-select-manufacturer',
    filterProperty: '.filter-multi-select-properties',
    filterPrice: '.filter-range',
    filterPriceMin: '.filter-range input[name="min-price"]',
    filterPriceMax: '.filter-range input[name="max-price"]',
    activeFilterContainer: '.filter-panel-active-container',
    activeFilter: '.filter-active',
    resetAllFilters: '.filter-reset-all',
    emptyResult: '.alert-info',
  },
  search: {
    headline: '.search-headline',
    emptyAlert: '.alert-info',
  },
  product: {
    name: '.product-detail-name',
    price: '.product-detail-price',
    productNumber: '.product-detail-ordernumber',
    buyForm: '.product-detail-buy form, form.buy-widget',
    buyButton: '.product-detail-buy .btn-buy',
    quantityInput: '.product-detail-buy .js-quantity-selector',
    quantityPlus: '.product-detail-buy .js-btn-plus',
    configurator: '.product-detail-configurator',
    configuratorGroup: '.product-detail-configurator-group',
    configuratorOption: '.product-detail-configurator-option',
    configuratorOptionLabel: '.product-detail-configurator-option-label',
    configuratorOptionInput: '.product-detail-configurator-option-input',
    gallery: '.product-detail-media, .gallery-slider',
    galleryImage: '.gallery-slider-image, .product-detail-media img',
    description: '.product-detail-description',
    properties: '.product-detail-properties',
    tabs: '.product-detail-tabs',
    reviewTeaser: '.product-detail-review-teaser',
    delivery: '.product-detail-delivery-information, .delivery-information',
    tax: '.product-detail-tax',
    wishlistButton: '.product-wishlist-action, .product-wishlist-btn',
    crossSelling: '.product-cross-selling, .cms-element-cross-selling',
  },
  offcanvasCart: {
    root: '.cart-offcanvas.show, .offcanvas.cart-offcanvas.show',
    lineItem: '.offcanvas-cart .line-item-product',
    lineItemLabel: '.line-item-label',
    quantityInput: '.js-quantity-selector',
    plus: '.js-btn-plus',
    minus: '.js-btn-minus',
    remove: '.line-item-remove-button',
    checkoutButton: '.begin-checkout-btn',
    cartLink: 'a[href$="/checkout/cart"]',
    close: '.offcanvas-close',
    empty: '.offcanvas-cart .alert-info, .offcanvas-cart .cart-empty',
  },
  cart: {
    root: '.checkout',
    lineItem: '.line-item-product',
    lineItemLabel: '.line-item-label',
    quantityInput: '.line-item-quantity .js-quantity-selector',
    plus: '.line-item-quantity .js-btn-plus',
    minus: '.line-item-quantity .js-btn-minus',
    remove: '.line-item-remove-button',
    lineItemTotal: '.line-item-total-price-value',
    summaryTotal: 'dd.checkout-aside-summary-total',
    summaryList: '.checkout-aside-summary-list',
    checkoutButton: '.checkout-aside-action .begin-checkout-btn, a.begin-checkout-btn',
    promotionInput: 'form.cart-add-promotion input[name="code"]',
    promotionSubmit: '.checkout-aside-add-promotion-button',
    empty: '.checkout .alert-info',
    itemCounter: '.cart-main-header-item-counter',
  },
  login: {
    form: 'form.login-form',
    email: '#loginMail',
    password: '#loginPassword',
    submit: 'form.login-form button[type="submit"]',
    collapseToggle: '.login-collapse-toggle',
  },
  register: {
    form: 'form.register-form',
    salutation: '#personalSalutation',
    firstName: '[name="billingAddress[firstName]"]',
    lastName: '[name="billingAddress[lastName]"]',
    email: '#personalMail',
    password: '#personalPassword',
    createAccount: 'input[name="createCustomerAccount"]',
    street: '[name="billingAddress[street]"]',
    zipcode: '[name="billingAddress[zipcode]"]',
    city: '[name="billingAddress[city]"]',
    country: '[name="billingAddress[countryId]"]',
    countryState: '[name="billingAddress[countryStateId]"]',
    differentShipping: '.js-different-shipping-checkbox',
    dataProtection: '[name="acceptedDataProtection"]',
    submit: 'button[type="submit"]', // scoped to register form
  },
  account: {
    overview: '.account-overview, .account-welcome',
    aside: '.account-aside',
    asideItem: '.account-aside-item',
    profileForm: '#profilePersonalForm',
    profileFirstName: '#profilePersonalForm [name="firstName"]',
    profileLastName: '#profilePersonalForm [name="lastName"]',
    profileSubmit: '#profilePersonalForm button[type="submit"]',
    addressCard: '.address-card, .address-box',
    addAddressButton: 'a[href*="/account/address/create"]',
    orderItem: '.order-table, .order-wrapper, .account-order-overview .order-item',
    logout: 'a[href$="/account/logout"]',
  },
  checkout: {
    confirmForm: '#confirmOrderForm',
    tos: '#tos',
    submitOrder: '#confirmFormSubmit',
    paymentMethod: '.payment-method-input',
    paymentMethodLabel: '.payment-method-label',
    shippingMethod: '.shipping-method-input',
    shippingMethodLabel: '.shipping-method-label',
    address: '.confirm-address',
    lineItem: '.line-item-product',
    finishHeader: '.finish-header',
    finishOrderNumber: '.finish-ordernumber',
  },
  contact: {
    form: 'form[action$="/form/contact"]',
    salutation: '[name="salutationId"]',
    firstName: '[name="firstName"]',
    lastName: '[name="lastName"]',
    email: '[name="email"]',
    phone: '[name="phone"]',
    subject: '[name="subject"]',
    comment: '[name="comment"]',
    submit: 'button[type="submit"]',
    success: '.confirm-message, .alert-success',
  },
  footer: {
    root: 'footer, .footer-main',
    link: 'footer a',
    bottom: '.footer-bottom',
  },
  error: {
    /** Shopware sets body.is-ctl-error on error pages */
    body: 'body.is-ctl-error',
    backToShop: 'main a[href]',
  },
  wishlist: {
    page: '.cms-listing-row, .wishlist-listing',
    productBox: '.product-box',
    remove: '.product-wishlist-remove, .product-wishlist-action',
  },
};

export type Selectors = typeof shopware67Selectors;
